// data-grammar.js — грамматический справочник (тестовый набор, будет расширен на ШАГЕ 6)
const GRAMMAR = [
  {
    id: 'gr-a1-1',
    level: 'A1',
    title: 'Артикли der/die/das',
    explanation: 'В немецком языке у каждого существительного есть род: мужской (der), женский (die) или средний (das). Род нужно запоминать вместе со словом — не всегда есть логика. Артикль стоит перед существительным и меняется по падежам.',
    table: {
      headers: ['Род', 'Артикль', 'Пример'],
      rows: [
        ['Мужской 🔵', 'der', 'der Mann (мужчина)'],
        ['Женский 🔴', 'die', 'die Frau (женщина)'],
        ['Средний 🟢', 'das', 'das Kind (ребёнок)'],
      ],
    },
    mnemonic: 'Совет: учите каждое существительное сразу с артиклем и цветом, как единое слово: "дэр Ман", "ди Фрау", "дас Кинд".',
    examples: [
      { de: 'Der Tisch ist groß.', ru: 'Стол большой.' },
      { de: 'Die Küche ist klein.', ru: 'Кухня маленькая.' },
      { de: 'Das Zimmer ist hell.', ru: 'Комната светлая.' },
      { de: 'Der Bahnhof ist weit.', ru: 'Вокзал далеко.' },
      { de: 'Die Familie isst zusammen.', ru: 'Семья ест вместе.' },
    ],
  },
  {
    id: 'gr-a1-2',
    level: 'A1',
    title: 'Präsens (настоящее время) правильных глаголов',
    explanation: 'Большинство немецких глаголов в настоящем времени спрягаются по стандартной схеме: убираем -en от инфинитива и добавляем окончания в зависимости от лица.',
    table: {
      headers: ['Лицо', 'Окончание', 'machen (делать)'],
      rows: [
        ['ich', '-e', 'ich mache'],
        ['du', '-st', 'du machst'],
        ['er/sie/es', '-t', 'er macht'],
        ['wir', '-en', 'wir machen'],
        ['ihr', '-t', 'ihr macht'],
        ['sie/Sie', '-en', 'sie machen'],
      ],
    },
    mnemonic: 'Мнемоника: "e-st-t-en-t-en" — пропой как считалку.',
    examples: [
      { de: 'Ich wohne in Berlin.', ru: 'Я живу в Берлине.' },
      { de: 'Du arbeitest viel.', ru: 'Ты много работаешь.' },
      { de: 'Er spielt Fußball.', ru: 'Он играет в футбол.' },
      { de: 'Wir kaufen Brot.', ru: 'Мы покупаем хлеб.' },
      { de: 'Sie lernen Deutsch.', ru: 'Они учат немецкий.' },
    ],
  },
  {
    id: 'gr-a1-3',
    level: 'A1',
    title: 'Глаголы sein и haben',
    explanation: 'Sein («быть») и haben («иметь») — самые важные и самые неправильные глаголы немецкого языка. Они спрягаются не по стандартной схеме, их формы нужно просто выучить наизусть. Они также используются как вспомогательные глаголы для образования прошедшего времени Perfekt.',
    table: {
      headers: ['Лицо', 'sein', 'haben'],
      rows: [
        ['ich', 'bin', 'habe'],
        ['du', 'bist', 'hast'],
        ['er/sie/es', 'ist', 'hat'],
        ['wir', 'sind', 'haben'],
        ['ihr', 'seid', 'habt'],
        ['sie/Sie', 'sind', 'haben'],
      ],
    },
    mnemonic: 'Запомните пару "ich bin — ich habe" как единое целое: это фундамент, на котором строится вся немецкая грамматика.',
    examples: [
      { de: 'Ich bin Student.', ru: 'Я студент.' },
      { de: 'Du hast einen Hund.', ru: 'У тебя есть собака.' },
      { de: 'Er ist müde.', ru: 'Он устал.' },
      { de: 'Wir haben Zeit.', ru: 'У нас есть время.' },
      { de: 'Sie sind glücklich.', ru: 'Они счастливы.' },
    ],
  },
  {
    id: 'gr-a1-4',
    level: 'A1',
    title: 'Модальные глаголы (können, müssen, wollen, dürfen, sollen, mögen)',
    explanation: 'Модальные глаголы выражают возможность, необходимость, желание, разрешение или совет. Они изменяются нестандартно в единственном числе, а смысловой глагол в предложении всегда стоит в инфинитиве в конце предложения.',
    table: {
      headers: ['Глагол', 'Значение', 'ich / du / er'],
      rows: [
        ['können', 'мочь, уметь', 'kann / kannst / kann'],
        ['müssen', 'быть должным', 'muss / musst / muss'],
        ['wollen', 'хотеть', 'will / willst / will'],
        ['dürfen', 'иметь разрешение', 'darf / darfst / darf'],
        ['sollen', 'быть должным (совет)', 'soll / sollst / soll'],
        ['mögen', 'нравиться', 'mag / magst / mag'],
      ],
    },
    mnemonic: 'Модальный глагол — «якорь» на втором месте, а смысловой глагол уплывает в конец предложения, как лодка на верёвке.',
    examples: [
      { de: 'Ich kann gut schwimmen.', ru: 'Я хорошо умею плавать.' },
      { de: 'Du musst früh aufstehen.', ru: 'Тебе нужно рано вставать.' },
      { de: 'Er will ein neues Auto kaufen.', ru: 'Он хочет купить новую машину.' },
      { de: 'Wir dürfen hier nicht rauchen.', ru: 'Нам нельзя здесь курить.' },
      { de: 'Du sollst mehr Wasser trinken.', ru: 'Тебе следует пить больше воды.' },
    ],
  },
  {
    id: 'gr-a1-5',
    level: 'A1',
    title: 'Отрицание: nicht и kein',
    explanation: '«Kein» используется для отрицания существительных с неопределённым артиклем или без артикля (kein Auto, kein Wasser). «Nicht» отрицает глаголы, прилагательные, наречия и существительные с определённым артиклем. Nicht обычно стоит перед отрицаемым словом или в конце предложения, если отрицается весь глагол.',
    table: {
      headers: ['Случай', 'Отрицание', 'Пример'],
      rows: [
        ['Существительное без артикля', 'kein/keine', 'Ich habe kein Geld.'],
        ['Глагол', 'nicht (в конце)', 'Ich verstehe nicht.'],
        ['Прилагательное', 'nicht (перед словом)', 'Das ist nicht teuer.'],
        ['Определённый артикль', 'nicht', 'Ich mag den Film nicht.'],
      ],
    },
    mnemonic: 'Правило: «есть артикль ein/eine — используй kein/keine; во всех остальных случаях — nicht».',
    examples: [
      { de: 'Ich habe keine Zeit.', ru: 'У меня нет времени.' },
      { de: 'Das ist nicht mein Buch.', ru: 'Это не моя книга.' },
      { de: 'Wir gehen heute nicht ins Kino.', ru: 'Мы сегодня не идём в кино.' },
      { de: 'Sie hat kein Auto.', ru: 'У неё нет машины.' },
      { de: 'Das Wetter ist nicht schön.', ru: 'Погода нехорошая.' },
    ],
  },
  {
    id: 'gr-a1-6',
    level: 'A1',
    title: 'Винительный падеж (Akkusativ)',
    explanation: 'Akkusativ используется для прямого дополнения — того, на что направлено действие («вижу кого? что?»). Изменяется только артикль мужского рода: der → den, ein → einen. Женский, средний род и множественное число не меняются.',
    table: {
      headers: ['Род', 'Nominativ', 'Akkusativ'],
      rows: [
        ['Мужской 🔵', 'der / ein', 'den / einen'],
        ['Женский 🔴', 'die / eine', 'die / eine'],
        ['Средний 🟢', 'das / ein', 'das / ein'],
        ['Множ. число', 'die', 'die'],
      ],
    },
    mnemonic: 'Меняется только «мужчина»: der → den, ein → einen. Всё остальное остаётся как было — это правило легко запомнить.',
    examples: [
      { de: 'Ich sehe den Mann.', ru: 'Я вижу мужчину.' },
      { de: 'Sie kauft einen Apfel.', ru: 'Она покупает яблоко.' },
      { de: 'Wir lesen ein Buch.', ru: 'Мы читаем книгу.' },
      { de: 'Er liebt die Musik.', ru: 'Он любит музыку.' },
      { de: 'Hast du einen Bruder?', ru: 'У тебя есть брат?' },
    ],
  },
  {
    id: 'gr-a1-7',
    level: 'A1',
    title: 'Притяжательные местоимения',
    explanation: 'Притяжательные местоимения (мой, твой, его и т.д.) склоняются как неопределённый артикль ein: в мужском и среднем роде окончания нет, в женском роде и множественном числе добавляется -e.',
    table: {
      headers: ['Лицо', 'Местоимение', 'мужской/средний', 'женский/мн.ч.'],
      rows: [
        ['ich', 'mein', 'mein Vater', 'meine Mutter'],
        ['du', 'dein', 'dein Haus', 'deine Familie'],
        ['er', 'sein', 'sein Auto', 'seine Tasche'],
        ['sie', 'ihr', 'ihr Kind', 'ihre Katze'],
        ['wir', 'unser', 'unser Garten', 'unsere Wohnung'],
      ],
    },
    mnemonic: 'Притяжательные местоимения ведут себя точно как «ein»: без окончания для der/das-слов, с окончанием -e для die-слов.',
    examples: [
      { de: 'Das ist mein Bruder.', ru: 'Это мой брат.' },
      { de: 'Wo ist deine Tasche?', ru: 'Где твоя сумка?' },
      { de: 'Sein Handy ist neu.', ru: 'Его телефон новый.' },
      { de: 'Ihre Schwester wohnt in Köln.', ru: 'Её сестра живёт в Кёльне.' },
      { de: 'Unser Auto ist rot.', ru: 'Наша машина красная.' },
    ],
  },
  {
    id: 'gr-a1-8',
    level: 'A1',
    title: 'Повелительное наклонение (Imperativ)',
    explanation: 'Imperativ используется для просьб, советов и команд. Форма для «du» образуется от основы глагола без окончания -st (иногда с -e), форма для «ihr» совпадает с обычной формой настоящего времени, а вежливая форма «Sie» ставит глагол перед местоимением.',
    table: {
      headers: ['Форма', 'kommen', 'Beispiel'],
      rows: [
        ['du', 'Komm!', 'Komm her!'],
        ['ihr', 'Kommt!', 'Kommt bitte her!'],
        ['Sie', 'Kommen Sie!', 'Kommen Sie bitte herein!'],
      ],
    },
    mnemonic: 'Для «Sie»-формы просто переставь подлежащее и сказуемое местами: «Sie kommen» → «Kommen Sie!».',
    examples: [
      { de: 'Öffne bitte das Fenster!', ru: 'Открой, пожалуйста, окно!' },
      { de: 'Setzt euch bitte hin!', ru: 'Садитесь, пожалуйста!' },
      { de: 'Seien Sie bitte pünktlich!', ru: 'Будьте, пожалуйста, пунктуальны!' },
      { de: 'Hilf mir bitte!', ru: 'Помоги мне, пожалуйста!' },
      { de: 'Nehmen Sie bitte Platz!', ru: 'Присаживайтесь, пожалуйста!' },
    ],
  },
  {
    id: 'gr-a1-9',
    level: 'A1',
    title: 'Основные предлоги и падежи',
    explanation: 'Каждый немецкий предлог требует определённого падежа. Некоторые предлоги всегда требуют Akkusativ (винительный), другие — Dativ (дательный). Их нужно запомнить как устойчивые группы.',
    table: {
      headers: ['Всегда Akkusativ', 'Всегда Dativ'],
      rows: [
        ['durch, für, gegen, ohne, um', 'aus, bei, mit, nach, seit, von, zu'],
      ],
    },
    mnemonic: 'Для Akkusativ-предлогов есть считалка "durch-für-gegen-ohne-um" (dfgou), а для Dativ — "aus-bei-mit-nach-seit-von-zu" (пропой как одну фразу).',
    examples: [
      { de: 'Das Geschenk ist für dich.', ru: 'Подарок для тебя.' },
      { de: 'Ich gehe ohne dich.', ru: 'Я иду без тебя.' },
      { de: 'Sie kommt aus Spanien.', ru: 'Она из Испании.' },
      { de: 'Wir fahren mit dem Bus.', ru: 'Мы едем на автобусе.' },
      { de: 'Er wohnt seit einem Jahr hier.', ru: 'Он живёт здесь уже год.' },
    ],
  },
  {
    id: 'gr-a1-10',
    level: 'A1',
    title: 'Порядок слов в предложении',
    explanation: 'В немецком повествовательном предложении спрягаемый глагол всегда стоит на втором месте (это правило V2). Первое место может занимать подлежащее, обстоятельство или дополнение — но глагол не сдвигается со второй позиции. В вопросах без вопросительного слова глагол стоит на первом месте.',
    table: {
      headers: ['Позиция 1', 'Позиция 2 (глагол)', 'Остальное'],
      rows: [
        ['Ich', 'lerne', 'heute Deutsch.'],
        ['Heute', 'lerne', 'ich Deutsch.'],
        ['Deutsch', 'lerne', 'ich heute.'],
      ],
    },
    mnemonic: 'Правило «V2»: неважно, что стоит на первом месте, глагол всегда занимает второе — как якорь в предложении.',
    examples: [
      { de: 'Morgen fahre ich nach Berlin.', ru: 'Завтра я еду в Берлин.' },
      { de: 'Ich fahre morgen nach Berlin.', ru: 'Я еду завтра в Берлин.' },
      { de: 'Nach Berlin fahre ich morgen.', ru: 'В Берлин я еду завтра.' },
      { de: 'Kommst du heute mit?', ru: 'Ты идёшь сегодня с нами?' },
      { de: 'Wann beginnt der Film?', ru: 'Когда начинается фильм?' },
    ],
  },
  {
    id: 'gr-a1-11',
    level: 'A1',
    title: 'Слияние предлога с артиклем (im, am, zum, zur, ins, ans)',
    explanation: 'Некоторые предлоги очень часто сливаются с определённым артиклем в один короткий вариант — так же, как в русском "у него" иногда сокращают в речи. Это не отдельное правило падежей, а просто удобное сокращение: "in dem" всегда можно (а в устойчивых выражениях — нужно) сократить до "im", "an dem" — до "am", "zu dem" — до "zum", "zu der" — до "zur", "in das" — до "ins", "an das" — до "ans". Это касается только мужского/среднего рода в дательном падеже и среднего рода в винительном.',
    table: {
      headers: ['Полная форма', 'Сокращение', 'Пример'],
      rows: [
        ['in dem', 'im', 'im Haus (в доме)'],
        ['an dem', 'am', 'am Montag (в понедельник)'],
        ['zu dem', 'zum', 'zum Bahnhof (к вокзалу)'],
        ['zu der', 'zur', 'zur Schule (в школу)'],
        ['in das', 'ins', 'ins Kino (в кино)'],
        ['an das', 'ans', 'ans Meer (к морю)'],
      ],
    },
    mnemonic: 'im = in+dem, am = an+dem, zum = zu+dem, zur = zu+der: обе буквы первого слова + начало артикля. Без слияния так тоже можно сказать, но носители почти всегда используют короткую форму.',
    examples: [
      { de: 'Das Buch liegt im Regal.', ru: 'Книга лежит в шкафу.' },
      { de: 'Wir treffen uns am Wochenende.', ru: 'Мы встретимся на выходных.' },
      { de: 'Ich gehe zum Arzt.', ru: 'Я иду к врачу.' },
      { de: 'Sie fährt zur Arbeit.', ru: 'Она едет на работу.' },
      { de: 'Die Kinder gehen ins Kino.', ru: 'Дети идут в кино.' },
    ],
  },

  // ===================== A2 =====================
  {
    id: 'gr-a2-1',
    level: 'A2',
    title: 'Дательный падеж (Dativ)',
    explanation: 'Dativ используется для косвенного дополнения — того, кому или для кого совершается действие («даю кому?»), а также после определённых предлогов и глаголов. В Dativ меняются артикли всех родов, а в множественном числе к существительному добавляется -n.',
    table: {
      headers: ['Род', 'Nominativ', 'Dativ'],
      rows: [
        ['Мужской 🔵', 'der / ein', 'dem / einem'],
        ['Женский 🔴', 'die / eine', 'der / einer'],
        ['Средний 🟢', 'das / ein', 'dem / einem'],
        ['Множ. число', 'die', 'den + n'],
      ],
    },
    mnemonic: 'В Dativ у мужского и среднего рода одна и та же форма «dem», а множественное число получает окончание -n у существительного: den Kindern.',
    examples: [
      { de: 'Ich gebe dem Kind ein Geschenk.', ru: 'Я даю ребёнку подарок.' },
      { de: 'Sie hilft ihrer Mutter.', ru: 'Она помогает своей маме.' },
      { de: 'Wir danken den Lehrern.', ru: 'Мы благодарим учителей.' },
      { de: 'Das gehört einem Freund von mir.', ru: 'Это принадлежит моему другу.' },
      { de: 'Er schreibt seiner Schwester einen Brief.', ru: 'Он пишет письмо своей сестре.' },
    ],
  },
  {
    id: 'gr-a2-2',
    level: 'A2',
    title: 'Двухпадежные предлоги (Wechselpräpositionen)',
    explanation: 'Девять предлогов (an, auf, hinter, in, neben, über, unter, vor, zwischen) могут требовать как Akkusativ, так и Dativ. Akkusativ используется при вопросе «куда?» (движение, изменение места), Dativ — при вопросе «где?» (нахождение на месте).',
    table: {
      headers: ['Вопрос', 'Падеж', 'Пример'],
      rows: [
        ['Wohin? (куда?)', 'Akkusativ', 'Ich lege das Buch auf den Tisch.'],
        ['Wo? (где?)', 'Dativ', 'Das Buch liegt auf dem Tisch.'],
      ],
    },
    mnemonic: 'Куда? — движение — Akkusativ (в конечную точку). Где? — покой — Dativ (место остановилось).',
    examples: [
      { de: 'Ich stelle die Tasche in den Schrank.', ru: 'Я ставлю сумку в шкаф.' },
      { de: 'Die Tasche steht im Schrank.', ru: 'Сумка стоит в шкафу.' },
      { de: 'Die Katze springt auf das Sofa.', ru: 'Кошка прыгает на диван.' },
      { de: 'Die Katze sitzt auf dem Sofa.', ru: 'Кошка сидит на диване.' },
      { de: 'Er hängt das Bild an die Wand.', ru: 'Он вешает картину на стену.' },
    ],
  },
  {
    id: 'gr-a2-3',
    level: 'A2',
    title: 'Perfekt (разговорное прошедшее время)',
    explanation: 'Perfekt — основное время для рассказа о прошлом в разговорной речи. Образуется вспомогательным глаголом haben или sein в настоящем времени + Partizip II смыслового глагола в конце предложения. Sein используется с глаголами движения и изменения состояния, остальные — с haben.',
    table: {
      headers: ['Тип глагола', 'Вспомогательный', 'Пример'],
      rows: [
        ['Большинство глаголов', 'haben', 'Ich habe gegessen.'],
        ['Движение/изменение состояния', 'sein', 'Ich bin gefahren.'],
        ['Правильные глаголы', 'ge- + основа + -t', 'gemacht, gekauft'],
        ['Неправильные глаголы', 'ge- + основа + -en', 'gegessen, gefahren'],
      ],
    },
    mnemonic: 'Проверка на «sein»: если глагол значит движение из точки А в точку Б (fahren, gehen, kommen) или изменение состояния (aufwachen, sterben) — бери sein, иначе haben.',
    examples: [
      { de: 'Ich habe gestern gearbeitet.', ru: 'Я вчера работал.' },
      { de: 'Wir sind ins Kino gegangen.', ru: 'Мы пошли в кино.' },
      { de: 'Hast du das Buch gelesen?', ru: 'Ты прочитал книгу?' },
      { de: 'Sie ist nach Berlin gefahren.', ru: 'Она поехала в Берлин.' },
      { de: 'Er hat einen Kaffee getrunken.', ru: 'Он выпил кофе.' },
    ],
  },
  {
    id: 'gr-a2-4',
    level: 'A2',
    title: 'Придаточные предложения: weil, dass, wenn, ob',
    explanation: 'Эти союзы вводят придаточное предложение, в котором спрягаемый глагол уходит в самый конец. Weil объясняет причину («потому что»), dass вводит объектное придаточное («что»), wenn — условие или повторяющееся время («если/когда»), ob — косвенный вопрос («ли»).',
    table: {
      headers: ['Союз', 'Значение', 'Пример'],
      rows: [
        ['weil', 'потому что', 'Ich bleibe zu Hause, weil ich krank bin.'],
        ['dass', 'что', 'Ich weiß, dass du recht hast.'],
        ['wenn', 'если/когда', 'Ich rufe an, wenn ich Zeit habe.'],
        ['ob', 'ли', 'Ich weiß nicht, ob er kommt.'],
      ],
    },
    mnemonic: 'После этих союзов глагол «убегает» в конец предложения — представь, что союз выталкивает его назад.',
    examples: [
      { de: 'Wir bleiben zu Hause, weil es regnet.', ru: 'Мы остаёмся дома, потому что идёт дождь.' },
      { de: 'Er sagt, dass er müde ist.', ru: 'Он говорит, что устал.' },
      { de: 'Wenn ich Zeit habe, besuche ich dich.', ru: 'Если у меня будет время, я тебя навещу.' },
      { de: 'Ich frage mich, ob sie glücklich ist.', ru: 'Я спрашиваю себя, счастлива ли она.' },
      { de: 'Sie lernt Deutsch, weil sie in Deutschland arbeiten möchte.', ru: 'Она учит немецкий, потому что хочет работать в Германии.' },
    ],
  },
  {
    id: 'gr-a2-5',
    level: 'A2',
    title: 'Сравнение прилагательных (Komparation)',
    explanation: 'У прилагательных есть три степени сравнения: положительная (обычная форма), сравнительная (добавляется -er) и превосходная (am + основа + -sten). Многие короткие прилагательные получают умлаут в сравнительной и превосходной степени.',
    table: {
      headers: ['Положительная', 'Сравнительная', 'Превосходная'],
      rows: [
        ['schnell', 'schneller', 'am schnellsten'],
        ['groß', 'größer', 'am größten'],
        ['gut', 'besser', 'am besten'],
        ['gern', 'lieber', 'am liebsten'],
        ['viel', 'mehr', 'am meisten'],
      ],
    },
    mnemonic: 'Три исключения нужно просто выучить наизусть: gut-besser-am besten, gern-lieber-am liebsten, viel-mehr-am meisten.',
    examples: [
      { de: 'Mein Auto ist schneller als deins.', ru: 'Моя машина быстрее твоей.' },
      { de: 'Das ist das größte Haus der Stadt.', ru: 'Это самый большой дом в городе.' },
      { de: 'Sie kocht besser als ich.', ru: 'Она готовит лучше меня.' },
      { de: 'Ich trinke am liebsten Tee.', ru: 'Больше всего я люблю пить чай.' },
      { de: 'Im Sommer arbeite ich am meisten.', ru: 'Летом я работаю больше всего.' },
    ],
  },
  {
    id: 'gr-a2-6',
    level: 'A2',
    title: 'Возвратные глаголы',
    explanation: 'Возвратные глаголы используются с возвратным местоимением (sich), которое изменяется по лицам. Многие немецкие возвратные глаголы не переводятся возвратными глаголами на русском (sich freuen — радоваться), поэтому их нужно запоминать целиком вместе с местоимением.',
    table: {
      headers: ['Лицо', 'Местоимение', 'sich freuen'],
      rows: [
        ['ich', 'mich', 'ich freue mich'],
        ['du', 'dich', 'du freust dich'],
        ['er/sie/es', 'sich', 'er freut sich'],
        ['wir', 'uns', 'wir freuen uns'],
        ['ihr', 'euch', 'ihr freut euch'],
        ['sie/Sie', 'sich', 'sie freuen sich'],
      ],
    },
    mnemonic: 'Только третье лицо (er/sie/es и sie/Sie) использует «sich» — все остальные формы совпадают с обычными личными местоимениями в Akkusativ.',
    examples: [
      { de: 'Ich freue mich auf die Ferien.', ru: 'Я радуюсь предстоящим каникулам.' },
      { de: 'Setz dich bitte hin.', ru: 'Присядь, пожалуйста.' },
      { de: 'Wir treffen uns um sieben Uhr.', ru: 'Мы встречаемся в семь часов.' },
      { de: 'Er interessiert sich für Musik.', ru: 'Он интересуется музыкой.' },
      { de: 'Erinnerst du dich an mich?', ru: 'Ты меня помнишь?' },
    ],
  },
  {
    id: 'gr-a2-7',
    level: 'A2',
    title: 'Склонение прилагательных',
    explanation: 'Окончание прилагательного перед существительным зависит от рода, падежа и от того, какой артикль стоит перед прилагательным (определённый, неопределённый или его отсутствие). После определённого артикля окончания слабые (в основном -e/-en), после неопределённого — сильнее выражают род и падеж.',
    table: {
      headers: ['Артикль', 'Мужской (Nom.)', 'Женский (Nom.)', 'Средний (Nom.)'],
      rows: [
        ['определённый', 'der neue Tisch', 'die neue Lampe', 'das neue Auto'],
        ['неопределённый', 'ein neuer Tisch', 'eine neue Lampe', 'ein neues Auto'],
      ],
    },
    mnemonic: 'Если артикль уже «показал» род (der/die/das) — прилагательное расслабляется и берёт слабое -e/-en. Если артикль «молчит» (ein, ein) — прилагательное берёт окончание артикля на себя.',
    examples: [
      { de: 'Ich habe einen neuen Freund.', ru: 'У меня новый друг.' },
      { de: 'Das ist die schöne Aussicht.', ru: 'Это красивый вид.' },
      { de: 'Wir wohnen in einem alten Haus.', ru: 'Мы живём в старом доме.' },
      { de: 'Sie trägt ein rotes Kleid.', ru: 'Она носит красное платье.' },
      { de: 'Der kleine Hund schläft.', ru: 'Маленькая собака спит.' },
    ],
  },
  {
    id: 'gr-a2-8',
    level: 'A2',
    title: 'Konjunktiv II (würde/hätte/wäre)',
    explanation: 'Konjunktiv II выражает нереальные, гипотетические ситуации, вежливые просьбы и пожелания («я бы сделал», «если бы»). В разговорной речи чаще всего используется конструкция würde + инфинитив, а hätte и wäre используются самостоятельно как формы haben и sein в сослагательном наклонении.',
    table: {
      headers: ['Глагол', 'Форма Konjunktiv II', 'Пример'],
      rows: [
        ['sein', 'wäre', 'Ich wäre gern reich.'],
        ['haben', 'hätte', 'Ich hätte gern einen Kaffee.'],
        ['любой глагол', 'würde + Infinitiv', 'Ich würde gern reisen.'],
      ],
    },
    mnemonic: 'Вежливая просьба всегда звучит мягче с Konjunktiv II: сравни «Ich will» (грубо) и «Ich hätte gern» (вежливо).',
    examples: [
      { de: 'Ich hätte gern ein Glas Wasser.', ru: 'Я хотел бы стакан воды.' },
      { de: 'Wenn ich Zeit hätte, würde ich mehr reisen.', ru: 'Если бы у меня было время, я бы больше путешествовал.' },
      { de: 'Das wäre sehr nett von dir.', ru: 'Это было бы очень мило с твоей стороны.' },
      { de: 'Würdest du mir bitte helfen?', ru: 'Не мог бы ты мне помочь?' },
      { de: 'An deiner Stelle würde ich das nicht tun.', ru: 'На твоём месте я бы этого не делал.' },
    ],
  },

  // ===================== B1 =====================
  {
    id: 'gr-b1-1',
    level: 'B1',
    title: 'Präteritum (простое прошедшее время)',
    explanation: 'Präteritum используется преимущественно в письменной речи, рассказах и для sein/haben/модальных глаголов даже в разговорной речи. Правильные глаголы получают суффикс -te, неправильные меняют корневую гласную по особым формам, которые нужно запоминать.',
    table: {
      headers: ['Глагол', 'Präteritum (ich)', 'Тип'],
      rows: [
        ['machen', 'machte', 'правильный'],
        ['sein', 'war', 'неправильный'],
        ['haben', 'hatte', 'неправильный'],
        ['gehen', 'ging', 'неправильный'],
        ['können', 'konnte', 'модальный'],
      ],
    },
    mnemonic: 'В устной речи почти всегда используй Perfekt, а Präteritum обязателен только для sein (war), haben (hatte) и модальных глаголов — они звучат естественнее в этой форме.',
    examples: [
      { de: 'Es war einmal eine Prinzessin.', ru: 'Жила-была принцесса.' },
      { de: 'Ich hatte keine Zeit gestern.', ru: 'У меня вчера не было времени.' },
      { de: 'Wir gingen jeden Tag spazieren.', ru: 'Мы каждый день ходили гулять.' },
      { de: 'Sie konnte nicht kommen.', ru: 'Она не могла прийти.' },
      { de: 'Er machte seine Hausaufgaben.', ru: 'Он делал домашнее задание.' },
    ],
  },
  {
    id: 'gr-b1-2',
    level: 'B1',
    title: 'Plusquamperfekt (предпрошедшее время)',
    explanation: 'Plusquamperfekt обозначает действие, которое произошло раньше другого действия в прошлом («уже сделал до того как»). Образуется как Präteritum глаголов haben/sein + Partizip II. Часто используется вместе с союзом nachdem.',
    table: {
      headers: ['Часть', 'Форма', 'Пример'],
      rows: [
        ['Вспомогательный (Präteritum)', 'hatte / war', 'ich hatte, ich war'],
        ['Partizip II', 'в конце предложения', 'gemacht, gegangen'],
        ['Полная форма', 'hatte/war + Partizip II', 'Ich hatte das schon gemacht.'],
      ],
    },
    mnemonic: 'Plusquamperfekt — это «прошлое прошлого»: сначала произошло действие в Plusquamperfekt, а уже потом — действие в Präteritum/Perfekt.',
    examples: [
      { de: 'Nachdem ich gegessen hatte, ging ich spazieren.', ru: 'После того как я поел, я пошёл гулять.' },
      { de: 'Sie hatte den Film schon gesehen.', ru: 'Она уже видела этот фильм раньше.' },
      { de: 'Wir waren angekommen, bevor es dunkel wurde.', ru: 'Мы уже прибыли, прежде чем стемнело.' },
      { de: 'Er hatte vergessen, die Tür abzuschließen.', ru: 'Он забыл запереть дверь (до того).' },
      { de: 'Ich hatte nicht gewusst, dass du hier wohnst.', ru: 'Я не знал раньше, что ты здесь живёшь.' },
    ],
  },
  {
    id: 'gr-b1-3',
    level: 'B1',
    title: 'Futur I (будущее время)',
    explanation: 'Futur I образуется вспомогательным глаголом werden + инфинитив смыслового глагола в конце предложения. Используется для предсказаний, обещаний и намерений, хотя в разговорной речи будущее часто выражается настоящим временем с указанием времени.',
    table: {
      headers: ['Лицо', 'werden', 'Пример'],
      rows: [
        ['ich', 'werde', 'ich werde arbeiten'],
        ['du', 'wirst', 'du wirst arbeiten'],
        ['er/sie/es', 'wird', 'er wird arbeiten'],
        ['wir', 'werden', 'wir werden arbeiten'],
      ],
    },
    mnemonic: 'Futur I = werden (изменяемая часть) + инфинитив (неизменная часть в конце) — как обычный модальный глагол.',
    examples: [
      { de: 'Ich werde morgen anrufen.', ru: 'Я позвоню завтра.' },
      { de: 'Es wird bald regnen.', ru: 'Скоро пойдёт дождь.' },
      { de: 'Wir werden das Problem lösen.', ru: 'Мы решим эту проблему.' },
      { de: 'Wirst du an der Konferenz teilnehmen?', ru: 'Ты будешь участвовать в конференции?' },
      { de: 'Sie werden bald ankommen.', ru: 'Они скоро прибудут.' },
    ],
  },
  {
    id: 'gr-b1-4',
    level: 'B1',
    title: 'Пассивный залог (Passiv)',
    explanation: 'Passiv используется, когда важно само действие, а не тот, кто его совершает. Образуется вспомогательным глаголом werden + Partizip II. Деятель, если он упоминается, вводится предлогом von (для одушевлённых) или durch (для причин/средств).',
    table: {
      headers: ['Время', 'Форма', 'Пример'],
      rows: [
        ['Präsens', 'werden + Partizip II', 'Das Haus wird gebaut.'],
        ['Präteritum', 'wurde + Partizip II', 'Das Haus wurde gebaut.'],
        ['Perfekt', 'ist + Partizip II + worden', 'Das Haus ist gebaut worden.'],
      ],
    },
    mnemonic: 'Активное «X делает Y» превращается в пассивное «Y делается (кем-то)»: подлежащее и дополнение как будто меняются местами.',
    examples: [
      { de: 'Das Auto wird repariert.', ru: 'Машину ремонтируют.' },
      { de: 'Der Brief wurde gestern geschrieben.', ru: 'Письмо было написано вчера.' },
      { de: 'Die Regeln müssen befolgt werden.', ru: 'Правила должны соблюдаться.' },
      { de: 'Das Gebäude wurde von einem berühmten Architekten entworfen.', ru: 'Здание было спроектировано знаменитым архитектором.' },
      { de: 'Die Fenster werden jede Woche geputzt.', ru: 'Окна моют каждую неделю.' },
    ],
  },
  {
    id: 'gr-b1-5',
    level: 'B1',
    title: 'Относительные придаточные предложения (Relativsätze)',
    explanation: 'Relativsätze уточняют существительное с помощью относительных местоимений (der, die, das в соответствующем падеже), которые склоняются как определённый артикль. Глагол в относительном придаточном уходит в конец предложения, а само придаточное выделяется запятыми.',
    table: {
      headers: ['Падеж', 'Мужской', 'Женский', 'Средний', 'Мн. число'],
      rows: [
        ['Nominativ', 'der', 'die', 'das', 'die'],
        ['Akkusativ', 'den', 'die', 'das', 'die'],
        ['Dativ', 'dem', 'der', 'dem', 'denen'],
      ],
    },
    mnemonic: 'Относительное местоимение выбирается по роду главного слова, а падеж — по его роли внутри придаточного предложения.',
    examples: [
      { de: 'Der Mann, der dort steht, ist mein Chef.', ru: 'Мужчина, который там стоит, — мой начальник.' },
      { de: 'Das ist die Frau, die ich gestern getroffen habe.', ru: 'Это женщина, которую я вчера встретил.' },
      { de: 'Ich kenne den Film, den du meinst.', ru: 'Я знаю фильм, который ты имеешь в виду.' },
      { de: 'Das Buch, das auf dem Tisch liegt, gehört mir.', ru: 'Книга, которая лежит на столе, принадлежит мне.' },
      { de: 'Die Kinder, denen ich geholfen habe, waren dankbar.', ru: 'Дети, которым я помог, были благодарны.' },
    ],
  },
  {
    id: 'gr-b1-6',
    level: 'B1',
    title: 'Родительный падеж (Genitiv)',
    explanation: 'Genitiv выражает принадлежность («чей?»). В разговорной речи он часто заменяется конструкцией с von + Dativ, но в письменной речи и на экзамене B1 нужно уметь им пользоваться. У существительных мужского и среднего рода в единственном числе добавляется окончание -(e)s.',
    table: {
      headers: ['Род', 'Nominativ', 'Genitiv'],
      rows: [
        ['Мужской 🔵', 'der Mann', 'des Mannes'],
        ['Женский 🔴', 'die Frau', 'der Frau'],
        ['Средний 🟢', 'das Kind', 'des Kindes'],
        ['Множ. число', 'die Kinder', 'der Kinder'],
      ],
    },
    mnemonic: 'Только мужской и средний род «получают хвостик» -(e)s на существительное, а артикль всегда переходит в des/der.',
    examples: [
      { de: 'Das ist das Auto meines Vaters.', ru: 'Это машина моего отца.' },
      { de: 'Die Farbe des Himmels ist blau.', ru: 'Цвет неба — синий.' },
      { de: 'Trotz des Regens gehen wir spazieren.', ru: 'Несмотря на дождь, мы идём гулять.' },
      { de: 'Das ist die Tasche der Lehrerin.', ru: 'Это сумка учительницы.' },
      { de: 'Während des Urlaubs habe ich viel gelesen.', ru: 'Во время отпуска я много читал.' },
    ],
  },
  {
    id: 'gr-b1-7',
    level: 'B1',
    title: 'N-склонение существительных (N-Deklination)',
    explanation: 'Небольшая группа существительных мужского рода (обычно обозначающих людей и животных, например der Student, der Junge, der Herr) получает окончание -en или -n во всех падежах, кроме Nominativ единственного числа.',
    table: {
      headers: ['Падеж', 'ед. число', 'мн. число'],
      rows: [
        ['Nominativ', 'der Student', 'die Studenten'],
        ['Akkusativ', 'den Studenten', 'die Studenten'],
        ['Dativ', 'dem Studenten', 'den Studenten'],
        ['Genitiv', 'des Studenten', 'der Studenten'],
      ],
    },
    mnemonic: 'Только Nominativ единственного числа остаётся «голым» — во всех остальных случаях слово получает окончание -en, как приклеенный хвостик.',
    examples: [
      { de: 'Ich sehe den Studenten.', ru: 'Я вижу студента.' },
      { de: 'Er hilft dem Jungen.', ru: 'Он помогает мальчику.' },
      { de: 'Das ist das Auto des Herrn.', ru: 'Это машина господина.' },
      { de: 'Wir sprechen mit dem Kollegen.', ru: 'Мы разговариваем с коллегой.' },
      { de: 'Sie kennt den Präsidenten.', ru: 'Она знает президента.' },
    ],
  },
  {
    id: 'gr-b1-8',
    level: 'B1',
    title: 'Конструкции um...zu и ohne...zu',
    explanation: '«Um...zu + Infinitiv» выражает цель действия («чтобы сделать что-то»), а «ohne...zu + Infinitiv» выражает действие, которое не сопровождается чем-то ожидаемым («не делая»). Обе конструкции используются, когда подлежащее в главном и придаточном предложении совпадает.',
    table: {
      headers: ['Конструкция', 'Значение', 'Пример'],
      rows: [
        ['um...zu', 'чтобы', 'Ich lerne, um die Prüfung zu bestehen.'],
        ['ohne...zu', 'не делая, без того чтобы', 'Er ging, ohne sich zu verabschieden.'],
      ],
    },
    mnemonic: '«Um...zu» отвечает на вопрос «зачем?», а «ohne...zu» описывает то, чего НЕ произошло по пути к цели.',
    examples: [
      { de: 'Ich gehe einkaufen, um Brot zu kaufen.', ru: 'Я иду за покупками, чтобы купить хлеб.' },
      { de: 'Sie spart Geld, um ein Auto zu kaufen.', ru: 'Она копит деньги, чтобы купить машину.' },
      { de: 'Er verließ den Raum, ohne etwas zu sagen.', ru: 'Он вышел из комнаты, ничего не сказав.' },
      { de: 'Wir lernen Deutsch, um in Deutschland zu arbeiten.', ru: 'Мы учим немецкий, чтобы работать в Германии.' },
      { de: 'Sie aß, ohne mit uns zu sprechen.', ru: 'Она ела, не разговаривая с нами.' },
    ],
  },
  {
    id: 'gr-b1-9',
    level: 'B1',
    title: 'Двойные союзы (zwar...aber, entweder...oder и другие)',
    explanation: 'Двойные союзы связывают два элемента предложения парами. Они помогают строить более сложные и выразительные высказывания, характерные для уровня B1 в письменной и устной речи.',
    table: {
      headers: ['Союз', 'Значение', 'Пример'],
      rows: [
        ['zwar...aber', 'хотя... но', 'Er ist zwar müde, aber er arbeitet weiter.'],
        ['entweder...oder', 'либо... либо', 'Entweder du kommst mit, oder ich gehe allein.'],
        ['weder...noch', 'ни... ни', 'Sie hat weder Zeit noch Geld.'],
        ['sowohl...als auch', 'как... так и', 'Er spricht sowohl Deutsch als auch Englisch.'],
      ],
    },
    mnemonic: 'Каждая пара союзов работает как «два крючка», которые вешают на себя два равноправных элемента предложения.',
    examples: [
      { de: 'Zwar regnet es, aber wir gehen trotzdem spazieren.', ru: 'Хотя идёт дождь, мы всё равно идём гулять.' },
      { de: 'Entweder wir bleiben zu Hause, oder wir fahren weg.', ru: 'Либо мы остаёмся дома, либо уезжаем.' },
      { de: 'Weder meine Schwester noch mein Bruder war da.', ru: 'Ни моя сестра, ни мой брат не были там.' },
      { de: 'Sie ist sowohl klug als auch fleißig.', ru: 'Она как умная, так и трудолюбивая.' },
      { de: 'Er will weder kochen noch abwaschen.', ru: 'Он не хочет ни готовить, ни мыть посуду.' },
    ],
  },
  {
    id: 'gr-b1-10',
    level: 'B1',
    title: 'Косвенная речь (indirekte Rede)',
    explanation: 'Косвенная речь передаёт слова другого человека без цитирования. В официальном стиле используется Konjunktiv I (er komme, sie sei), но в разговорной речи чаще используется обычный индикатив или Konjunktiv II, если формы Konjunktiv I совпадают с индикативом.',
    table: {
      headers: ['Прямая речь', 'Косвенная речь (Konjunktiv I)'],
      rows: [
        ['Er sagt: "Ich bin müde."', 'Er sagt, er sei müde.'],
        ['Sie sagt: "Ich habe Zeit."', 'Sie sagt, sie habe Zeit.'],
        ['Er sagt: "Ich komme morgen."', 'Er sagt, er komme morgen.'],
      ],
    },
    mnemonic: 'Konjunktiv I образуется от основы инфинитива + личные окончания (er komme, wie «ich» + e): «глагол становится вежливым отражением себя самого».',
    examples: [
      { de: 'Er behauptet, er sei unschuldig.', ru: 'Он утверждает, что он невиновен.' },
      { de: 'Sie sagte, dass sie krank sei.', ru: 'Она сказала, что она больна.' },
      { de: 'Er meinte, er habe keine Zeit.', ru: 'Он сказал, что у него нет времени.' },
      { de: 'Die Zeitung schrieb, die Preise würden steigen.', ru: 'Газета написала, что цены вырастут.' },
      { de: 'Er fragte, ob ich morgen komme.', ru: 'Он спросил, приду ли я завтра.' },
    ],
  },

  // ===================== B2 =====================
  {
    id: 'gr-b2-1',
    level: 'B2',
    title: 'Konjunktiv I: полная система косвенной речи',
    explanation: 'На уровне B2 нужно уверенно образовывать Konjunktiv I для ВСЕХ лиц и времён, а не только "er/sie/es". Konjunktiv I образуется от основы инфинитива + окончания -e, -est, -e, -en, -et, -en. Если форма Konjunktiv I совпадает с обычным индикативом (особенно во множественном числе), её заменяют на Konjunktiv II, чтобы косвенная речь была отличима от прямой. Это правило журналисты и официальные документы используют постоянно.',
    table: {
      headers: ['Лицо', 'sagen → Konjunktiv I', 'Если совпадает с индикативом'],
      rows: [
        ['ich', 'ich sage (→ Konjunktiv II: ich sagte)', 'заменяется'],
        ['du', 'du sagest', 'используется редко'],
        ['er/sie/es', 'er sage', 'стандартная форма'],
        ['wir', 'wir sagen (= индикатив!)', '→ wir würden sagen'],
        ['ihr', 'ihr saget', 'используется редко'],
        ['sie/Sie', 'sie sagen (= индикатив!)', '→ sie würden sagen'],
      ],
    },
    mnemonic: 'Правило: если Konjunktiv I "неотличим" от обычного настоящего времени — берём Konjunktiv II (часто через würde + Infinitiv). Это встречается почти всегда в "wir" и "sie/Sie".',
    examples: [
      { de: 'Die Firma teilte mit, sie werde neue Stellen schaffen.', ru: 'Компания сообщила, что создаст новые рабочие места.' },
      { de: 'Die Wissenschaftler erklärten, sie hätten neue Beweise gefunden.', ru: 'Учёные заявили, что нашли новые доказательства.' },
      { de: 'Der Politiker sagte, er wolle die Steuern senken.', ru: 'Политик сказал, что хочет снизить налоги.' },
      { de: 'Sie behaupteten, sie würden bald zurückkommen.', ru: 'Они утверждали, что скоро вернутся.' },
      { de: 'Der Sprecher erklärte, man werde die Lage genau beobachten.', ru: 'Спикер заявил, что ситуацию будут внимательно отслеживать.' },
    ],
  },
  {
    id: 'gr-b2-2',
    level: 'B2',
    title: 'Партиципиальные конструкции (Partizip I / II как определения)',
    explanation: 'Причастия в немецком часто используются как прилагательные перед существительным — это типично для письменного и официального стиля и позволяет сокращать придаточные предложения. Partizip I (der lesende Mann = "читающий мужчина") выражает одновременное, активное действие. Partizip II (das gelesene Buch = "прочитанная книга") выражает завершённое или пассивное действие. Расширенные партиципиальные конструкции (erweiterte Partizipialattribute) добавляют перед причастием дополнительные слова.',
    table: {
      headers: ['Придаточное предложение', 'Партиципиальная конструкция'],
      rows: [
        ['der Mann, der am Fenster sitzt', 'der am Fenster sitzende Mann'],
        ['das Buch, das gestern gekauft wurde', 'das gestern gekaufte Buch'],
        ['die Kinder, die im Park spielen', 'die im Park spielenden Kinder'],
      ],
    },
    mnemonic: 'Partizip I = "-end" = делающий (активно, сейчас); Partizip II = "ge-...-t/-en" = сделанный (пассивно, завершено). Расширенная конструкция читается справа налево: сначала найдите причастие, потом разверните всё, что перед ним.',
    examples: [
      { de: 'Die steigenden Preise beunruhigen viele Verbraucher.', ru: 'Растущие цены беспокоят многих потребителей.' },
      { de: 'Das vor einem Jahr gegründete Unternehmen wächst schnell.', ru: 'Компания, основанная год назад, быстро растёт.' },
      { de: 'Die aus Deutschland stammende Familie lebt seit Jahren hier.', ru: 'Семья, родом из Германии, живёт здесь уже много лет.' },
      { de: 'Der schlafende Hund lag ruhig auf dem Sofa.', ru: 'Спящая собака спокойно лежала на диване.' },
      { de: 'Die von der Regierung vorgeschlagenen Reformen sind umstritten.', ru: 'Реформы, предложенные правительством, спорны.' },
    ],
  },
  {
    id: 'gr-b2-3',
    level: 'B2',
    title: 'Номинальный стиль (Nominalisierung)',
    explanation: 'Официальные тексты, доклады и научные статьи в немецком часто "превращают" глаголы в существительные — это называется номинализацией. Вместо "Weil die Preise steigen, ..." пишут "Wegen des Preisanstiegs, ...". Такой стиль более компактный и формальный, но труднее для чтения — нужно уметь "разворачивать" номинализированные фразы обратно в предложения с глаголом, чтобы понимать смысл.',
    table: {
      headers: ['Глагольный стиль (разговорный)', 'Номинальный стиль (официальный)'],
      rows: [
        ['weil die Preise steigen', 'wegen des Preisanstiegs'],
        ['nachdem die Verhandlungen beendet wurden', 'nach Beendigung der Verhandlungen'],
        ['indem man die Kosten senkt', 'durch die Senkung der Kosten'],
        ['wenn man das Gesetz ändert', 'bei einer Änderung des Gesetzes'],
      ],
    },
    mnemonic: 'Типичные суффиксы номинализированных существительных: -ung, -heit, -keit, -tion, -e (die Senkung, die Änderung, die Reduktion). Увидев такое существительное после предлога (wegen, durch, bei, nach) — мысленно превращайте его обратно в глагол с союзом.',
    examples: [
      { de: 'Wegen der Verspätung des Zuges kam er zu spät zur Arbeit.', ru: 'Из-за опоздания поезда он опоздал на работу.' },
      { de: 'Durch die Digitalisierung verändern sich viele Berufe.', ru: 'Из-за цифровизации меняются многие профессии.' },
      { de: 'Nach Abschluss des Studiums begann sie sofort zu arbeiten.', ru: 'После окончания учёбы она сразу начала работать.' },
      { de: 'Bei Nichteinhaltung der Frist drohen Konsequenzen.', ru: 'При несоблюдении срока грозят последствия.' },
      { de: 'Die Erhöhung der Steuern führte zu Protesten.', ru: 'Повышение налогов привело к протестам.' },
    ],
  },
  {
    id: 'gr-b2-4',
    level: 'B2',
    title: 'Пассив с модальными глаголами и Zustandspassiv',
    explanation: 'Пассив (страдательный залог) может сочетаться с модальными глаголами: müssen, können, sollen + werden + Partizip II. Отдельно существует Zustandspassiv (пассив состояния) с sein вместо werden — он описывает не процесс, а РЕЗУЛЬТАТ действия, уже наступившее состояние.',
    table: {
      headers: ['Тип', 'Формула', 'Пример'],
      rows: [
        ['Vorgangspassiv (процесс)', 'werden + Partizip II', 'Die Tür wird geöffnet. (дверь открывают)'],
        ['Passiv + модальный глагол', 'модальный + Partizip II + werden', 'Die Tür muss geöffnet werden.'],
        ['Zustandspassiv (результат)', 'sein + Partizip II', 'Die Tür ist geöffnet. (дверь уже открыта)'],
      ],
    },
    mnemonic: 'werden = что-то ПРОИСХОДИТ (процесс); sein = что-то УЖЕ произошло, и мы видим результат (состояние). "Die Tür wird geöffnet" (сейчас открывают) vs "Die Tür ist geöffnet" (уже открыта, стоит открытая).',
    examples: [
      { de: 'Das Problem muss sofort gelöst werden.', ru: 'Проблему нужно немедленно решить.' },
      { de: 'Die Berichte können online eingesehen werden.', ru: 'Отчёты можно посмотреть онлайн.' },
      { de: 'Der Laden ist schon geschlossen.', ru: 'Магазин уже закрыт.' },
      { de: 'Das Fenster ist zerbrochen.', ru: 'Окно разбито (уже, состояние).' },
      { de: 'Die Aufgabe soll bis Montag erledigt werden.', ru: 'Задачу нужно выполнить до понедельника.' },
    ],
  },
  {
    id: 'gr-b2-5',
    level: 'B2',
    title: 'Сложные союзы: je...desto, sodass, indem, obwohl vs. trotzdem',
    explanation: 'На уровне B2 добавляются более тонкие связки между предложениями. "Je...desto" выражает пропорциональную зависимость (чем... тем...) и требует особого порядка слов в обеих частях. "Sodass" вводит следствие. "Indem" описывает способ действия (можно перевести как "тем, что" или деепричастием). Важно различать "obwohl" (союз, вводит придаточное с глаголом в конце) и "trotzdem" (наречие, стоит в самостоятельном предложении, не меняя его структуры на придаточную).',
    table: {
      headers: ['Союз/наречие', 'Значение', 'Позиция глагола'],
      rows: [
        ['je... desto...', 'чем... тем...', 'в обеих частях — конец/начало (V2)'],
        ['sodass', 'так что, вследствие чего', 'глагол в конце'],
        ['indem', 'тем, что / путём того, что', 'глагол в конце'],
        ['obwohl', 'хотя (союз)', 'глагол в конце придаточного'],
        ['trotzdem', 'несмотря на это (наречие)', 'глагол на 2-м месте'],
      ],
    },
    mnemonic: '"Obwohl" всегда тянет за собой отдельное придаточное с глаголом в конце. "Trotzdem" — это просто слово-связка в начале обычного предложения, глагол сразу после него (V2), как после любого наречия.',
    examples: [
      { de: 'Je mehr man übt, desto besser wird man.', ru: 'Чем больше тренируешься, тем лучше становишься.' },
      { de: 'Er war so müde, dass er sofort einschlief.', ru: 'Он был так устал, что сразу заснул.' },
      { de: 'Sie verbesserte ihr Deutsch, indem sie jeden Tag las.', ru: 'Она улучшила немецкий, читая каждый день.' },
      { de: 'Obwohl es regnete, gingen wir spazieren.', ru: 'Хотя шёл дождь, мы пошли гулять.' },
      { de: 'Es regnete. Trotzdem gingen wir spazieren.', ru: 'Шёл дождь. Несмотря на это, мы пошли гулять.' },
    ],
  },
  {
    id: 'gr-b2-6',
    level: 'B2',
    title: 'Функциональные глагольные конструкции (Funktionsverbgefüge)',
    explanation: 'Это устойчивые сочетания "глагол + существительное", которые вместе означают почти то же самое, что и простой глагол, но звучат более официально/канцелярски. Они очень часто встречаются в деловой переписке, новостях и официальных документах — их нужно запоминать целыми блоками, а не переводить дословно.',
    table: {
      headers: ['Функциональная конструкция', 'Простой глагол', 'Перевод'],
      rows: [
        ['in Kraft treten', 'gelten / beginnen', 'вступать в силу'],
        ['zur Verfügung stellen', 'geben', 'предоставлять'],
        ['Rücksicht nehmen (auf)', 'berücksichtigen', 'считаться (с чем-то)'],
        ['zum Ausdruck bringen', 'ausdrücken', 'выражать'],
        ['in Anspruch nehmen', 'nutzen / brauchen', 'использовать, задействовать'],
      ],
    },
    mnemonic: 'Эти конструкции — визитная карточка официального/делового немецкого. Начните с малого: выучите 5-10 самых частых, а дальше будете узнавать их паттерн (глагол + существительное + предлог) в новых текстах.',
    examples: [
      { de: 'Das neue Gesetz tritt am ersten Januar in Kraft.', ru: 'Новый закон вступает в силу первого января.' },
      { de: 'Die Firma stellt ihren Mitarbeitern einen Firmenwagen zur Verfügung.', ru: 'Компания предоставляет сотрудникам служебную машину.' },
      { de: 'Wir müssen auf seine Gefühle Rücksicht nehmen.', ru: 'Нам нужно считаться с его чувствами.' },
      { de: 'Sie brachte ihre Freude deutlich zum Ausdruck.', ru: 'Она явно выразила свою радость.' },
      { de: 'Er nimmt das Angebot gerne in Anspruch.', ru: 'Он охотно пользуется этим предложением.' },
    ],
  },
  {
    id: 'gr-b2-7',
    level: 'B2',
    title: 'Относительные придаточные с предлогом и Genitiv (dessen/deren)',
    explanation: 'На уровне B2 относительные придаточные усложняются: относительное местоимение может стоять после предлога (der Mann, MIT DEM ich spreche), а притяжательное значение выражается через dessen (его, для муж./ср. рода) и deren (её/их, для жен. рода и множественного числа) — это аналог "чей" в русском.',
    table: {
      headers: ['Тип', 'Пример'],
      rows: [
        ['Относительное + предлог', 'der Freund, MIT DEM ich reise (друг, С КОТОРЫМ я путешествую)'],
        ['dessen (его, чей — муж./ср.)', 'der Mann, DESSEN Auto kaputt ist (мужчина, ЧЬЯ машина сломана)'],
        ['deren (её/их, чья/чьи)', 'die Frau, DEREN Kinder studieren (женщина, ЧЬИ дети учатся)'],
      ],
    },
    mnemonic: 'dessen/deren НЕ склоняются по падежу того слова, к которому относятся дальше в предложении — они всегда стоят в начале придаточного и просто показывают принадлежность, а падеж определяет следующее за ними существительное.',
    examples: [
      { de: 'Das ist der Kollege, mit dem ich das Projekt mache.', ru: 'Это коллега, с которым я делаю проект.' },
      { de: 'Sie sucht eine Wohnung, in der sie ruhig arbeiten kann.', ru: 'Она ищет квартиру, в которой сможет спокойно работать.' },
      { de: 'Der Autor, dessen Buch ich gerade lese, lebt in Berlin.', ru: 'Автор, чью книгу я сейчас читаю, живёт в Берлине.' },
      { de: 'Das Unternehmen, dessen Gewinn stark gestiegen ist, expandiert.', ru: 'Компания, чья прибыль сильно выросла, расширяется.' },
      { de: 'Die Familie, deren Haus abgebrannt ist, bekam viel Unterstützung.', ru: 'Семья, чей дом сгорел, получила большую поддержку.' },
    ],
  },
  {
    id: 'gr-b2-8',
    level: 'B2',
    title: 'Konjunktiv II: вежливость, нереальные сравнения, als ob',
    explanation: 'Konjunktiv II на B2 применяется шире, чем "würde + Infinitiv": для вежливых просьб (Könnten Sie...?), гипотетических условий (Wenn ich Zeit hätte, würde ich...), и особенно для нереальных сравнений с "als ob"/"als wenn" ("как будто"), после которых используется Konjunktiv II, а не обычный индикатив.',
    table: {
      headers: ['Конструкция', 'Пример'],
      rows: [
        ['Вежливая просьба', 'Könnten Sie mir bitte helfen?'],
        ['Нереальное условие', 'Wenn ich reich wäre, würde ich reisen.'],
        ['als ob + Konjunktiv II', 'Er tut, als ob er nichts wüsste.'],
        ['Сожаление о прошлом', 'Ich hätte das gerne gewusst.'],
      ],
    },
    mnemonic: '"Als ob" всегда переключает мозг на Konjunktiv II — это сигнальное слово. После него глагол уезжает в конец придаточного, как в любом другом придаточном с союзом.',
    examples: [
      { de: 'Könntest du das Fenster bitte schließen?', ru: 'Не мог бы ты, пожалуйста, закрыть окно?' },
      { de: 'Wenn ich du wäre, würde ich das nicht tun.', ru: 'На твоём месте я бы этого не делал.' },
      { de: 'Sie tat, als ob sie mich nicht gesehen hätte.', ru: 'Она сделала вид, будто не видела меня.' },
      { de: 'Er redet, als wäre er der Chef hier.', ru: 'Он говорит так, будто он здесь начальник.' },
      { de: 'Das hätte ich nicht erwartet.', ru: 'Я бы этого не ожидал.' },
    ],
  },
  {
    id: 'gr-b2-9',
    level: 'B2',
    title: 'Связность текста: слова-заместители (dabei, dadurch, daran, davon)',
    explanation: 'Чтобы не повторять одно и то же существительное много раз, немецкий использует "da-" + предлог (dabei, dadurch, daran, davon, damit и т.д.) — они заменяют "предлог + это/то" и связывают предложения друг с другом. Это ключевой инструмент для написания связного текста уровня B2 (эссе, письма) вместо набора несвязанных фраз.',
    table: {
      headers: ['da-слово', 'Заменяет', 'Пример'],
      rows: [
        ['dabei', 'bei + это', 'Er kocht und hört dabei Musik. (при этом)'],
        ['dadurch', 'durch + это', 'Er lernte fleißig, dadurch bestand er die Prüfung. (благодаря этому)'],
        ['damit', 'mit + это / чтобы', 'Sie spart Geld, damit sie reisen kann. (чтобы)'],
        ['davon', 'von + это', 'Ich habe davon gehört. (об этом)'],
        ['daran', 'an + это', 'Ich erinnere mich daran. (об этом)'],
      ],
    },
    mnemonic: 'Если бы вместо существительного стояло "das" после предлога — предлог+das сливаются в da(r)+предлог. Перед гласной вставляется "r" (darauf, daran, darüber) для благозвучия.',
    examples: [
      { de: 'Sie hat viel gearbeitet und ist dadurch sehr erfolgreich geworden.', ru: 'Она много работала и благодаря этому стала очень успешной.' },
      { de: 'Ich interessiere mich sehr dafür.', ru: 'Я этим очень интересуюсь.' },
      { de: 'Wir sprechen später darüber.', ru: 'Мы поговорим об этом позже.' },
      { de: 'Er kam zu spät. Damit hatte niemand gerechnet.', ru: 'Он опоздал. Этого никто не ожидал.' },
      { de: 'Sie lernt jeden Tag, damit sie die Prüfung besteht.', ru: 'Она учится каждый день, чтобы сдать экзамен.' },
    ],
  },
  {
    id: 'gr-b2-10',
    level: 'B2',
    title: 'Языковой регистр: формальный и неформальный стиль',
    explanation: 'На уровне B2 важно различать регистры речи и уместно их использовать: неформальный (разговор с друзьями, короткие предложения, du, модальные частицы вроде "mal", "halt") и формальный (деловая переписка, Sie, номинальный стиль, полные придаточные предложения). Умение переключаться между регистрами — один из главных признаков уровня B2 на устном экзамене.',
    table: {
      headers: ['Неформально', 'Формально'],
      rows: [
        ['Kannst du mir mal helfen?', 'Könnten Sie mir bitte behilflich sein?'],
        ['Ich find das gut.', 'Ich halte das für eine gute Entscheidung.'],
        ['Wir müssen das schnell klären.', 'Diese Angelegenheit bedarf einer zeitnahen Klärung.'],
        ['Tut mir leid, kein Bock heute.', 'Ich bedaure, heute leider keine Zeit zu haben.'],
      ],
    },
    mnemonic: 'Формальный немецкий тяготеет к номинальному стилю (см. тему выше), длинным предложениям и Sie. Неформальный — к коротким фразам, модальным частицам (ja, doch, halt, eben, mal) и du.',
    examples: [
      { de: 'Könnten Sie mir bitte die Unterlagen zusenden?', ru: 'Не могли бы вы отправить мне документы?' },
      { de: 'Schick mir das mal, wenn du Zeit hast.', ru: 'Скинь мне это как-нибудь, когда будет время.' },
      { de: 'Wir bitten um Ihr Verständnis.', ru: 'Просим вашего понимания.' },
      { de: 'Ist schon okay, kein Stress.', ru: 'Да всё нормально, не парься.' },
      { de: 'Ich würde mich über eine baldige Antwort freuen.', ru: 'Буду рад скорому ответу.' },
    ],
  },
];
